### ISSUE TITLE
version 0.12.0 issue - when comparing pdf to snapshot

### ISSUE THREAD

**Issue by GiriReddy10** [moshensky/pdf-visual-diff#81]
I was on 0.9.0 version and comparison seems to be good. But with latest update to 0.12.0 - comparison started failing with below error 

TypeError: Image or Canvas expected

        at drawImageAtIntegerCoords (node_modules/pdfjs-dist/legacy/build/webpack:/pdf.js/src/display/canvas.js:261:9)
        at CanvasGraphics.paintInlineImageXObject (node_modules/pdfjs-dist/legacy/build/webpack:/pdf.js/src/display/canvas.js:2990:5)
        at CanvasGraphics.apply (node_modules/pdfjs-dist/legacy/build/webpack:/pdf.js/src/display/canvas.js:2879:10)
        at CanvasGraphics.executeOperatorList (node_modules/pdfjs-dist/legacy/build/webpack:/pdf.js/src/display/canvas.js:967:20)
        at InternalRenderTask._next (node_modules/pdfjs-dist/legacy/build/webpack:/pdf.js/src/display/api.js:3486:37)

**Comment by moshensky** [comment]
:wave: 

Version [0.11.0](https://github.com/moshensky/pdf-visual-diff/blob/master/CHANGELOG.md#0110--2024-09-11) updates pdfjs-dist to v4. Could you make sure that you don't have any stale packages and or provide a sample repro or steps for me to reproduce the issue?

**Comment by moshensky** [comment]
@GiriReddy10,

What versions of Node.js and npm are you using?

**Comment by GiriReddy10** [comment]
npm - 10.8.2
node - v20.17.0

**Comment by moshensky** [comment]
@GiriReddy10 thank you for submitting the issue. Could you please try out the latest 0.13.0 [changelog](https://github.com/moshensky/pdf-visual-diff/blob/master/CHANGELOG.md#0130--2024-11-27)

**Comment by GiriReddy10** [comment]
Works perfectly now with latest version. Thanks
